### ISSUE TITLE
If an activity is "Other" for d-portal, declare this on the activity page

### ISSUE THREAD

**Issue by stevieflow** [IATI/D-Portal#498]
(via #405) 

If an activity is declared as "Other" - we can get to a list:

http://www.d-portal.org/ctrack.html?search&country=AO#view=missing

There's mention at the top of this list that there are "Projects with invalid date ranges"

However, it might be worth a visual clue / help text on the actual activity page, as these activities can appear through all manner of searches

Something like: "The dates for this activity do not seem to be useful.  Please check with the publisher".  Or something - I can appreciate that theere might be a number of reasons (bad date format, missing dates, etc) - but dont think d-portal needs to provide specific validation reasons.  Just something that carries over to the activity page would be good

**Comment by notshi** [comment]
Thanks, @stevieflow.

Do you mean, declare it on the actual SAVI page?

There is a mild suggestion of what 'Other' means in the "How is the data calculated' section via the link you provided, further down the page. You can also get to that section by clicking on the 'About this Data' link.

Sorry, just want to clarify the context of use for declaring an activity as "Other" on a SAVI page. May have misunderstood entirely also!

**Comment by stevieflow** [comment]
Hi @notshi - thanks

Yes- I think I mean the actual activity page , which you can get to from the "Other" list - eg 

http://www.d-portal.org/ctrack.html?search&country=AO#view=missing

leads to

http://www.d-portal.org/ctrack.html?search&country=AO#view=act&aid=41AAA-20141-001

Just a warning / visual prompt about the dates (as that is why they are in Other?) would be useful, I think

**Comment by stevieflow** [comment]
I just created https://github.com/IATI/D-Portal/issues/683 - which I think supersedes this issue, now
