### ISSUE TITLE
Links to @ref pages (when the @ref is not a publisher)

### ISSUE THREAD

**Issue by stevieflow** [IATI/D-Portal#602]
When an organisation has a ''ref'' value populated (either in ''participating-org'' or ''transaction/provider /receiver-org'') d-portal will construct a URL based on 

http://d-portal.org/ctrack.html?publisher=[Value_in@ref_attribute]

When this ref is to an existing publisher, this obviously works fine.  However - not all organisations publish IATI data (yet)!

(we kind of discussed this liklihood in #506 )

Hence - in this (random) example: http://d-portal.org/ctrack.html?text_search=hats#view=act&aid=XM-OCHA-CBPF-NGA-20%2FNIG_ERF%2FSA1%2FP%2FUN%2F16492 a ref is given to an organisation, but this is not a publisher: 

http://d-portal.org/ctrack.html?publisher=XM-OCHA-CBPF-NGA75#view=main - and so the user is sent to a blank/empty page.

I can certainly understand why these URLs are auto minted.  However, I wondered if something other could be provided.  Just thinking out loud:

- only construct an active link when the ref matches the references for publishers in the d-portal database (thus removing the chance of someone running into a blank page)
- maintain these active links for publisher refs, and direct to a friendly 404 type page when a ref is not on the publisher list
- when a ref is not on the publisher list, link to a search for that ref (in the relevant element) - for example: 
http://d-portal.org/ctrack.html?aids=http%3A%2F%2Fd-portal.org%2Fdquery%3Fsql%3D%250Aselect%250A%250A*%250A%250Afrom%2520xson%2520where%2520root%253D%27%252Fiati-activities%252Fiati-activity%27%250A%250Alimit%252010%253B%250A%250ASELECT%2520DISTINCT%2520aid%2520FROM%2520xson%2520WHERE%250A(%250A%2509root%253D%27%252Fiati-activities%252Fiati-activity%252Fhumanitarian-scope%27%2520AND%250A%2509xson-%253E%253E%27%2540type%27%253D%271%27%2520AND%250A%2509xson-%253E%253E%27%2540vocabulary%27%253D%271-2%27%2520AND%250A%2509xson-%253E%253E%27%2540code%27%253D%27EP-2020-000012-001%27%250A)#view=main

(constructed with dquery ^ ) 

The last idea would be interesting, but perhaps places lots more overhead on both the site, server and the user.

Any thoughts welcome @notshi @xriss ( @andylolz ?) - I *think* the first idea ^ would be a helpful move...

**Comment by notshi** [comment]
Thanks, @stevieflow for raising this.

We might go for option 2 as probably the most useful way of handling this 'unknown' data.
Or rather, the page will display what we know of that ```@ref``` with links to dquery and probably the registry.

For instance, from the example you provided, we can get this [basic information from dquery](http://d-portal.org/dquery/#%0Aselect%0A%0Axson-%3E%3E'@ref'%20as%20reference,%20xson-%3E'/narrative'-%3E0-%3E%3E''%20as%20narrative,%20pid%20as%20publisher,%20count(*)%0A%0Afrom%20xson%20where%20root%20in%20('/iati-activities/iati-activity/participating-org','/iati-activities/iati-activity/transaction/provider-org','/iati-activities/iati-activity/transaction/receiver-org')%0Aand%20xson-%3E%3E'@ref'='XM-OCHA-CBPF-NGA75'%0Agroup%20by%201,%202,%20pid%0A%0Aorder%20by%204%20desc%0A%0Alimit%2010;%0A%0A) so we can display such things on this new page.

```
{

    result: [
        {
            reference: "XM-OCHA-CBPF-NGA75",
            narrative: "Nigeria Humanitarian Fund",
            publisher: "XM-OCHA-CBPF",
            count: "305"
        }
    ],
    duration: 4.71

}
```

**Comment by stevieflow** [comment]
Thanks @notshi 

Yes, that would be interesting - as at least the user would not be left in limbo.  Of course, this will be a conceptual shift within d-portal, as all pages based on organisations are tied to the ``reporting-org``, at present.  Hence, there'd need to be some onscreen support to let users know this data isn't published by the ``@ref`` - happy to advise

**Comment by stevieflow** [comment]
Perfect, thanks 

Feel free to close this @notshi
