### ISSUE TITLE
Participating Organization/Organisation Search

### ISSUE THREAD

**Issue by notshi** [IATI/D-Portal#613]
From https://iaticonnect.org/topic/participating-organizationorganisation-search

@Michelle-IOM

> In attempting to find how a participating organization has been classified by other publishers, I just realized that the data store appears to only allow for searching on IATI publishers in the participating organization field.  However the organization I'm looking for and many other participating organizations are not IATI publishers. 
> 
> I can also see in d-portal that I can search on the organization name in the free-text search bar and find that the organization is listed in many IATI files but I don't see a way to get a dump from d-portal that can help me compare the org type across all those publishers.  
> 
> In this particular instance I'm looking to see how GIZ is classified by other publishers.  (government, public private partnership, CSO)  But I have others that I need to look up so I need a method to do this repetitively for other organizations.
> 
> Questions: 
> 
> 1) Are there any data users out there with any advice on how to get to this data without going one-by-one into each activity spit out by D-Portal?
> 
> 2) Are there any publishers out there that are willing to tell me how you have classified GIZ in your files?
> 
> 3) Can someone from the IATI technical team explain why the data store search is restricted to publishers and is there is another way to get out all participating organizations regardless of publisher status? If there is no solutions I will advocate for a user case here. 
>

**Comment by notshi** [comment]
Hi @Michelle-IOM,

We are able to use dquery to come up with this query that might be useful - [Link](http://d-portal.org/dquery/#%0A%0Aselect%0A%0Axson-%3E%3E'@role'%20as%20role_,%20%0Axson-%3E%3E'@type'%20as%20type_,%20%0Axson-%3E'/narrative'-%3E0-%3E%3E''%20as%20narrative,%20%0Apid%20as%20publisher,%20%0Acount(*)%0A%0Afrom%20xson%20where%20root='/iati-activities/iati-activity/participating-org'%20%0Aand%20xson-%3E'/narrative'-%3E0-%3E%3E''%20like%20'%25(GIZ)%25'%0A%0Agroup%20by%20xson-%3E%3E'@role',%20%0Axson-%3E%3E'@type',%20%0Apid,%20%0Anarrative%0A%0Aorder%20by%205%20desc%0A%0Alimit%2020000;%0A)
You'll need to click on **Run Query** and wait for the results to load.

Alternatively, here are the results in [CSV](http://d-portal.org/dquery?form=csv&sql=select%0A%0Axson-%3E%3E%27%40role%27%20as%20role_%2Cxson-%3E%3E%27%40type%27%20as%20type_%2Cxson-%3E%27%2Fnarrative%27-%3E0-%3E%3E%27%27%20as%20narrative%2Cpid%20as%20publisher%2Ccount(*)%0A%0Afrom%20xson%20where%20root%3D%27%2Fiati-activities%2Fiati-activity%2Fparticipating-org%27%20and%20xson-%3E%27%2Fnarrative%27-%3E0-%3E%3E%27%27%20like%20%27%25(GIZ)%25%27%0A%0Agroup%20by%20xson-%3E%3E%27%40role%27%2Cxson-%3E%3E%27%40type%27%2Cpid%2Cnarrative%0A%0Aorder%20by%205%20desc%0A%0Alimit%2020000%3B%0A) and [JSON](http://d-portal.org/dquery?sql=select%0A%0Axson-%3E%3E%27%40role%27%20as%20role_%2Cxson-%3E%3E%27%40type%27%20as%20type_%2Cxson-%3E%27%2Fnarrative%27-%3E0-%3E%3E%27%27%20as%20narrative%2Cpid%20as%20publisher%2Ccount(*)%0A%0Afrom%20xson%20where%20root%3D%27%2Fiati-activities%2Fiati-activity%2Fparticipating-org%27%20and%20xson-%3E%27%2Fnarrative%27-%3E0-%3E%3E%27%27%20like%20%27%25(GIZ)%25%27%0A%0Agroup%20by%20xson-%3E%3E%27%40role%27%2Cxson-%3E%3E%27%40type%27%2Cpid%2Cnarrative%0A%0Aorder%20by%205%20desc%0A%0Alimit%2020000%3B%0A)

A snippet of what it looks like and what it means:
```
    role_: "4",
    type_: "70",
    narrative: "DEUTSCHE GESELLSCHAFT FUR INTERNATIONALE ZUSAMMENARBEIT (GIZ) GMBH",
    publisher: "XI-IATI-EC_DEVCO",
    count: "181"
```

Publisher XI-IATI-EC_DEVCO has GIZ listed in ```participating-org/narrative``` and the ```@role``` is assigned as 4 and ```@type``` is 70.
This publisher has listed GIZ 181 times in the ```participating-org``` element.

When we use references from the [Registry](https://iatiregistry.org/publisher?q=XI-IATI-EC_DEVCO&sort=title+asc) and [Standard](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/participating-org/), this can also be read as:

European Commission - Directorate-General for International Partnerships (DEVCO) has listed GIZ as a participating org with an Implementing role and Private Sector org type.

**Comment by Michelle-IOM** [comment]
Dear DevInt/D-Portal Team,

I very much appreciate your attempt at help here. Sadly, I am a finance professional and have very little understanding on how to get data out unless it is spoon fed to me.  I don’t have internal IT support either to have someone within our organization do it for me.  This is why I was really hoping there was a user friendly tool in existence but it seems from all the posts that there isn’t……yet.

Having said that I did click on the link and hit run query (that much I can do) as you instructed however it came back with the below error.

***@***.***D71BE5.393C41B0]

The same error was returned when I clicked on the CSV link.

Kind Regards,
Michelle

Michelle Y. Levesque
Senior Project Manager
Department of Resources Management (DRM)
International Organization for Migration (IOM)<http://www.iom.int/>
Geneva – Switzerland (GMT +1)
Office: +41-(0)22 717 94 83
Mobile: +41 (0)78 647 31 86
Email/Skype: ***@***.******@***.***>

www.iom.int<http://www.iom.int/>  I  Facebook<https://www.facebook.com/pg/IOM/posts/?ref=page_internal>   I  Twitter<https://twitter.com/unmigration>

***@***.***D71BE5.393C41B0]

**Comment by notshi** [comment]
Hi @Michelle-IOM,

Thanks for trying. It looks like there might be some browser plugins or similar issues preventing you from accessing the site.
However, hopefully by you raising this as a use case, the feature will be funded and developed as a user friendly tool by the data task force or the Secretariat.

Meanwhile, because you were able to specifically list out what you needed, we are able to use our internal tool to create a complex query to get some results.

I've attached an Excel file of the results (Github doesn't allow CSV attachments at the moment).
[GIZ_dquery.xlsx](https://github.com/devinit/D-Portal/files/6164224/GIZ_dquery.xlsx)

Hopefully you can access that.

**Comment by Michelle-IOM** [comment]
Hi Shi,

This is very helpful but at the risk of overstaying my welcome, I have a couple of clarifying questions about the returned data.

Is the Role and Type in relation to GIZ (column B) or the publisher who reference GIZ (column C)?

Is it possible to provide the org reference used for GIZ if one exists in the publisher’s data set.  I see “null” where no type is listed so “null” would be fine if no reference is provided. Oddly enough IOM isn’t in the list of publishers which has any reference to GIZ.  I know we have published 12 projects funded by them under the name GIZ - Deutsche Gesellschaft fur Internationale Zusammenarbeit GmbH with a org reference of DE-DAC-5-52.

We use the DAC code because we currently classify GIZ as part of the German government. But as the organization is also a listed company in Germany we could have just as correctly used DE-HRB-12394 which I pieced together using the IATI guidelines and the German registry of companies (HRB).  But the whole question is if it should be considered a government.  If the type listed in this file is meant to reflect how GIZ has been classified by other publishers, I can see that 10 - government, 15 – other public sector, 40 - multilateral, 70 – private sector and 90 - other have all been used.

Please don’t feel obligated to re-run the query.  I appreciate this is all just one request and ultimately I have a series of organizations I need this sort of data pull on.  GIZ was just an example as it is a current struggle. But to the extent this is something that is quick and can be replicated easily enough it is greatly appreciated.

Kind Regards,
Michelle


Michelle Y. Levesque
Senior Project Manager
Department of Resources Management (DRM)
International Organization for Migration (IOM)<http://www.iom.int/>
Geneva – Switzerland (GMT +1)
Office: +41-(0)22 717 94 83
Mobile: +41 (0)78 647 31 86
Email/Skype: ***@***.******@***.***>

www.iom.int<http://www.iom.int/>  I  Facebook<https://www.facebook.com/pg/IOM/posts/?ref=page_internal>   I  Twitter<https://twitter.com/unmigration>

***@***.***D71C08.631D0000]

**Comment by notshi** [comment]
Hi @Michelle-IOM,

Many thanks for adding in those extra information as it provides more information for a better query.

> Is the Role and Type in relation to GIZ (column B) or the publisher who reference GIZ (column C)?

Both role and type is in relation to GIZ.
All columns are what the publisher has published in the data about GIZ.
This explains why there are many different types of spelling for GIZ as a participating organisation.

I've edited the query to include the ```@ref``` so you can see what other publishers are using to reference GIZ.
I've also edited the query so that it searches the ```participating-org/narrative``` for any combinations of GIZ.
You should now be able to see IOM listed with12 counts of GIZ.
[GIZ_dquery1.xlsx](https://github.com/devinit/D-Portal/files/6165279/GIZ_dquery1.xlsx)

**Comment by Michelle-IOM** [comment]
Dear Shi,

This is FANTASTIC and exactly what I was looking for.  Now if I could only do what you do for so many other non-publishing participating organizations.  Don’t worry I won’t ask you to be my personal data extractor.  I so appreciate this already.

Kind Regards,
Michelle

Michelle Y. Levesque
Senior Project Manager
Department of Resources Management (DRM)
International Organization for Migration (IOM)<http://www.iom.int/>
Geneva – Switzerland (GMT +1)
Office: +41-(0)22 717 94 83
Mobile: +41 (0)78 647 31 86
Email/Skype: ***@***.******@***.***>

www.iom.int<http://www.iom.int/>  I  Facebook<https://www.facebook.com/pg/IOM/posts/?ref=page_internal>   I  Twitter<https://twitter.com/unmigration>

***@***.***D71C1F.9AD34560]

**Comment by notshi** [comment]
Hi @Michelle-IOM 

If you can get someone to do the following on a browser that works (preferably Firefox or Chrome without plugins), you can just edit one part of the query to suit your needs.

1. Copy the text below
```
select
xson->>'@role' as participating_org_role, 
xson->>'@type' as participating_org_type, 
xson->>'@ref' as participating_org_ref, 
xson->'/narrative'->0->>'' as narrative, 
pid as publisher, 
count(*)

from xson where root='/iati-activities/iati-activity/participating-org' 
and xson->'/narrative'->0->>'' like '%GIZ%'

group by
participating_org_role, 
participating_org_type, 
participating_org_ref,
pid, 
narrative

order by 6 desc
limit 20000;
```
2. Visit [dQuery](http://d-portal.org/dquery)
3. Click on the editor and Paste the text
4. Under 'Download XSON', click on **Download XSON as csv**

--------------------------------

This is what it should look like if you did steps 1-3
![Screenshot-20210318175507-697x453](https://user-images.githubusercontent.com/1515961/111673721-2a473d00-8813-11eb-8f0a-0067168ad6ad.png)
*This is the Editor part of the page*

If you look at line 10 on the Editor, you can replace GIZ with other participating orgs.
![Screenshot-20210318175733-400x23](https://user-images.githubusercontent.com/1515961/111674012-75615000-8813-11eb-82e7-28d208269257.png)

You need to make sure to keep the % at both ends of the name and there shouldn't be any spaces.
This is also case sensitive so you probably want to use uppercase or capitalise if that is how it is reported in the data.

You can then click on **Download XSON as csv** to download the csv after you make your changes.
