### ISSUE TITLE
Add COVID-19 sector code to quick search

### ISSUE THREAD

**Issue by notshi** [IATI/D-Portal#626]
Raised here - https://github.com/OCHA-DAP/covid19-data/issues/2

There is now a specific OECD DAC 5-digit sector code for COVID-19 (12264) as listed on https://iatistandard.org/en/iati-standard/203/codelists/sector/

There are currently 1055 projects and 14 publishers using that sector code:
http://d-portal.org/ctrack.html?sector_code=12264#view=main

Should we be adding this to the quick search on d-portal? @amy-silcock

**Comment by amy-silcock** [comment]
Hi @notshi,

I'll check with Petya and Sarah when they're back from leave. Sounds sensible to me and also means we should update our Covid publishing/use guidance. Thank you for highlighting.

**Comment by notshi** [comment]
Hi @amy-silcock just wondering if there are any updates on this, thanks!

**Comment by amy-silcock** [comment]
Hi @notshi, next week we should be releasing the mini consultation on updating the Covid 19 guidance update. Hoping to get these implemented end of October. I'll post here once it's out.

Our view is that d-portal should follow the IATI data use guidance on finding Covid related activities.

**Comment by amy-silcock** [comment]
The COVID-19 guidance consultation is live here: https://iaticonnect.org/Discussion-COVID-19-Guidance

Please do add your views.

**Comment by amy-silcock** [comment]
We can now add the sector code 12664  into the d-portal Covid quick search.

After consultation with the community, IATI is updating it's covid publishing and data access guidance to include this code: https://iaticonnect.org/Discussion-COVID-19-Guidance

**Comment by notshi** [comment]
Thanks, @amy-silcock - this is now live on d-portal.

Will the [guidance page](https://docs.google.com/document/d/11XTnrPw8K76JvBhFfnqo-1Z9BmgqzWv2bEz9QoDrw2k/edit) (currently linked to from the Glossary) also be updated to include this new guideline?
Or should we be linking to a different guidance page?

**Comment by amy-silcock** [comment]
Thanks Shi. We will update the guidance page shortly, I'll let you know if this ends up being a new link rather than the existing page.
