### ISSUE TITLE
Naming Conventions in D-Portal for Activities and Projects

### ISSUE THREAD

**Issue by DaveEade49** [IATI/D-Portal#645]
The following comment has been made to IATI Helpdesk via Ticket reference: 23478

_**Dear IATI colleagues,
ILO has released its data for 2022 to IATI and will now update them on quarterly basis. We are trying to promote the use of IATI data and start getting feedback from users.
According to the [IATI standard](https://iatistandard.org/en/iati-standard/203/activity-standard/#:~:text=Definition,grouping%20of%20work%20and%20resources.), publisher publish their data to IATI by “activity”, which “might be a large programme, a small project or another logical grouping of work and resources”. However d-portal refers to “projects” on most of its pages. This creates confusion.
Would it be possible to streamline the use of “activity” as the main term throughout the d-portal ?_**

I've contacted Shi about this and had the following response:

**_The decision to use 'Projects' was made in 2014 when d-portal was being developed. 
It was originally called 'Activities' but 'Projects' was preferred, presumably on the grounds that it reads more user-friendly than 'Activities'.
This was when IATI was still very new and we did not have the large user base that is now more familiar with the Standard.
It is relatively straightforward enough to make the global change; we would need to look at all instances of where 'projects' is being used on d-portal.
However this change will affect any teaching materials made by third-parties; eg. presentations, papers and videos by Bond, Publish What you Fund, etc._**

It is suggested that this be put on the backlog for future consideration.

**Comment by stevieflow** [comment]
I do agree that Projects is confusing, most certainly when talking in the context of the IATI standard, which has activities as it's core unit

I also appreciate the historical context

Perhaps as part of https://github.com/IATI/D-Portal/issues/660 this should be in play though

**Comment by stevieflow** [comment]
Linked to https://github.com/IATI/D-Portal/issues/664 - but closing this so we proceed through one ticket.  I mean issue!
