### ISSUE TITLE
New tag vocabulary - auto populate in d-portal?

### ISSUE THREAD

**Issue by stevieflow** [IATI/D-Portal#648]
Hi @xriss @notshi 

Over at https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/384 @akmiller01 and team will hopefully be merging this , so we have a new tag vocabulary 

I wanted to check whether d-portal would _automagically_ update with this new value, or whether an alert - via an issue like this - would be needed

Thanks!

**Comment by notshi** [comment]
Hi @stevieflow 

As this concerns updating a pre-existing codelist, it should _automagically_ be updated in d-portal by tomorrow.

However, do let me know if that is not the case.

**Comment by stevieflow** [comment]
Hi @notshi 

Perfect, thanks

Correct: [the magic happened](http://d-portal.org/ctrack.html?/tag@vocabulary=4#view=main) :)

**Comment by stevieflow** [comment]
Hi @notshi 

With d-preview, I noticed that the vocab is visible via the usual link:

http://c329d37b086fba2a755ca653b3edcfbd.d-preview.codeforiati.org/ctrack.html#view=act&aid=XI-IATI-EC_INTPA-2021%2F43458%2F0

but - hitting the savi link means it isnt http://c329d37b086fba2a755ca653b3edcfbd.d-preview.codeforiati.org/savi/?aid=XI-IATI-EC_INTPA-2021/43458/0

Thanks

**Comment by notshi** [comment]
Hi @stevieflow - that's a live d-portal link that takes you out of the sandbox; ie. out of d-preview so you're seeing live data.

This should probably be raised as an issue for d-preview.
