### ISSUE TITLE
Remove CRS data

### ISSUE THREAD

**Issue by stevieflow** [IATI/D-Portal#655]
It seems that the CRS data in d-portal:

- hasn't been updated since 2019 (so perhaps two updates out)
- place a limited on the data table, in that they are fixed around 2019 -- not defaulting to the current year (of IATI data)

I do not see any plan or activity to supply updated CRS data

Therefore - at a _technical_ level - how much effort is needed to remove CRS from d-portal?

**Comment by notshi** [comment]
Removing CRS means there will be gaps in the tables that display them.

Hence, this is more a layout design issue than a technical one.

**Comment by stevieflow** [comment]
Just to check, is the inclusion of CRS data the reason that the click through from a graph of "All years" still defaults to a table view of 2018-20?

eg: 

from 

https://d-portal.org/ctrack.html?reporting_ref=GB-GOV-1#view=main
![Firefox_Screenshot_2024-03-06T18-20-28 951Z](https://github.com/IATI/D-Portal/assets/1209944/40f70358-99f4-40fd-b9cd-e4d8f6e61d57)

to
https://d-portal.org/ctrack.html?reporting_ref=GB-GOV-1#view=countries
![Firefox_Screenshot_2024-03-06T18-21-07 557Z](https://github.com/IATI/D-Portal/assets/1209944/938167ae-954d-413f-a7c3-ccf0614cd8aa)

**Comment by notshi** [comment]
Yes - we use the CRS years for that table so it defaults to it.

**Comment by notshi** [comment]
Would be good to look at this soon and remove CRS?

**Comment by stevieflow** [comment]
@notshi yes agree - as that means we can default to a 2024 view, I think?

**Comment by notshi** [comment]
@stevieflow Yes! Shall we look further into this as part of a release sometime soon (blogpost on Connect for feedback beforehand, etc)?

**Comment by stevieflow** [comment]
> Shall we look further into this as part of a release sometime soon (blogpost on Connect for feedback beforehand, etc)?

Thanks - yes please

Just to remind me - what is the latest set of CRS data that is in d-portal?

**Comment by notshi** [comment]
That would be 2019 - all in [here](https://github.com/IATI/D-Portal/tree/master/dstore/csv).

**Comment by IsabelBirds** [comment]
Connect post up with 11/7/24 deadline for comments. 
https://www.iaticonnect.org/topic/d-portal-update-removing-outdated-crs-comparison-display

**Comment by stevieflow** [comment]
@notshi no comments or like in the post :(

But - I think we can proceed.  Thanks

**Comment by notshi** [comment]
No news is good news? Many thanks, both - we will proceed with the removal of CRS data and update here when that happens.

**Comment by notshi** [comment]
CRS data is currently hidden and both publisher and sector tables now default to 2024 view; ie. 2024 is now in the middle.

**Comment by stevieflow** [comment]
Great, thanks

Does that complete the CRS removal task, therefore?  Thanks

**Comment by notshi** [comment]
We are just being a bit cautious so it's not entirely removed, just hidden.

We'll go through with fine-tooth comb and remove it when we're sure this is all ok.
