### ISSUE TITLE
"About IATI Publisher" link is confusing 

### ISSUE THREAD

**Issue by robredpath** [IATI/D-Portal#656]
**Brief Description**
On the page for each activity there's a link that says  "About IATI Publisher", which I'm confused by

**Severity**
Low

**Issue Location**

On the page for each activity there's a link that says  "About IATI Publisher":

<img width="975" alt="Screenshot 2024-01-09 at 14 39 43" src="https://github.com/IATI/D-Portal/assets/641009/dd2d257e-0b99-4cd5-b80a-322c47afda2f">

This seems to link to https://www.iatiregistry.org/publisher/ on all activity pages (e.g. https://d-portal.org/ctrack.html?text_search=food#view=act&aid=US-GOV-1-720BHA23IO00060 ) as well as search result pages (e.g. https://d-portal.org/ctrack.html?text_search=food#view=active) 

This is a bit confusing, as there's now a tool called IATI Publisher. I'm also unsure what I expect when I click the link: I only clicked it because I wondered if it indicated that the publisher had used IATI Publisher!

What was the link intended to do? Can we remove it or fix and rename it, now that there's a tool called IATI Publisher?

**Comment by notshi** [comment]
The link was added from https://github.com/IATI/D-Portal/issues/437

It currently links to the generic publisher list on the registry if you are not looking at a specific publisher on d-portal or have chosen a publisher in the search.

Perhaps it should be renamed to, 'Contact Publisher' and be displayed only when a publisher can be determined.

**Comment by robredpath** [comment]
That makes a lot of sense, thanks!

> Perhaps it should be renamed to, 'Contact Publisher' and be displayed only when a publisher can be determined.

I like that idea :)

**Comment by notshi** [comment]
Link has been updated https://github.com/IATI/D-Portal/commit/b1fca011a2e76eda4b72ff1ae64de254ec1194ed.

There's also a link in the footer that has been updated with the same logic.

**Comment by stevieflow** [comment]
I think this is all resolved
