### ISSUE TITLE
Practical Action not updated on D-Portal

### ISSUE THREAD

**Issue by IsabelBirds** [IATI/D-Portal#658]
Practical Actions activity file was updated on the registry on 3/1/24, with 909 activities (https://iatiregistry.org/dataset/pa-activity).

The file:
* validates without errors both via the validator pipeline and using the url
* has updated on the dashboard http://dashboard.iatistandard.org/publisher/pa.html 
* successfully creates a d-preview via IATI CoVE

This update has not appeared on D-portal, which still has 896 activities https://d-portal.org/ctrack.html?&publisher=GB-COH-871954#view=main 

I can see a 403 error in the logs (https://d-portal.org/ctrack.html?#view=dash_sluglog&slug=pa-activity) but I'm not sure of the cause as the other tools have been able to access the data. Could you help me troubleshoot this please? :)

**Comment by IsabelBirds** [comment]
Thanks @xriss! I'll feedback to the publisher.

**Comment by practicalaction** [comment]
Hi @xriss 
Kal from Practical Action here.
Could you confirm the IP address(es) for your server, so that I can ensure they are whitelisted? 
I will also speak to our provider to make sure that dportal as a service isn't blocked. 
Thanks

**Comment by IsabelBirds** [comment]
Hi Kal (@practicalaction),

Generally we don't recommend the whitelisting approach as we have a large number of tools which need to access the data, and third party tools may also be blocked by the server.
I believe an IATI Connect post is upcoming to discuss this issue with the wider IATI Community - I can direct you to this once it has been uploaded?

Thanks!

**Comment by practicalaction** [comment]
Hi Isabel @IsabelBirds 
Thanks for coming back to me. I have moved our data onto a public GitHub repo, and can see that the import was successful. 
Based on that, I will keep using the public repo and run some internal training on its use. 
Thanks for your help!
Kal

**Comment by notshi** [comment]
Many thanks all - if the data is updating as expected, shall we close this issue?

**Comment by practical-action-iati** [comment]
Hi @notshi 
Yes - suitable for closure.
Thanks
