### ISSUE TITLE
Searching for participating-org ref of a publisher

### ISSUE THREAD

**Issue by stevieflow** [IATI/D-Portal#661]
Following on from the functionality added via https://github.com/IATI/D-Portal/issues/642

It seems - rightly - that if you click a link for an org reference that is a publisher, you are directed to the publisher page

eg:

![Firefox_Screenshot_2024-02-22T08-12-54 575Z](https://github.com/IATI/D-Portal/assets/1209944/b0afd929-1548-473c-8361-02a9406aebe6)

leads to : https://d-portal.org/ctrack.html?publisher=XM-DAC-41122#view=main - where we see all the activities from that publisher

With the advent of #642 , we now know (although access to this has been in place via advanced filters for a long while) that this page is also accessible : https://d-portal.org/ctrack.html?/participating-org@ref=XM-DAC-41122#view=main - this is the 47 publishers (which include *the* publisher!) that use this org reference in the participating-org/@ref element, across 23, 141 activities

Both of these views/pages in d-portal are very helpful and useful : this is not a suggestion to change the outcome of #642.  

I think my enquiry is that from a publisher page, it might be helpful to know that we could additional search for this publisher as a participating-org..

@robredpath @markbrough could have reckons, too!

**Comment by notshi** [comment]
We could add a link for that additional search like so.

![Screenshot_20240306_224737](https://github.com/IATI/D-Portal/assets/1515961/03ed0d1a-d0c1-4d2c-b8d6-2c72c9c6aa4f)

It would be interesting to see what this could look like for https://github.com/IATI/D-Portal/issues/660

**Comment by stevieflow** [comment]
Thanks @notshi 

Yes, that would be a good next step I think - it gives people access to that data, and is clearly labelled

**Comment by notshi** [comment]
This should now be live - please do let us know if anything is amiss!

**Comment by notshi** [comment]
Notes:

- If participating-org is not a publisher, the link should be removed ([eg](https://d-portal.org/ctrack.html?/participating-org@ref=ET-COA-152#view=main)).

- At the moment, the link ignores any search filters if those are used.

**Comment by stevieflow** [comment]
> If participating-org is not a publisher, the link should be removed ([eg](https://d-portal.org/ctrack.html?/participating-org@ref=ET-COA-152#view=main)).

Ah yes, that would be good.  Shall I create a new ticket for that?

**Comment by notshi** [comment]
Yes, please. Thanks, @stevieflow!

**Comment by stevieflow** [comment]
Done: https://github.com/IATI/D-Portal/issues/667 !
