### ISSUE TITLE
participating-org: listing of narratives used under a single @ref

### ISSUE THREAD

**Issue by stevieflow** [IATI/D-Portal#663]
Here's a simple mockup of what a participating-org section could look like.

![Screenshot 2022-03-26 at 15-06-04 d-portal](https://user-images.githubusercontent.com/1515961/160245530-925a42e7-9e32-45e9-86af-d3893c42296b.png)

_Originally posted by @notshi in https://github.com/IATI/D-Portal/issues/642#issuecomment-1079713762_

**Comment by stevieflow** [comment]
Referenced via https://github.com/IATI/D-Portal/issues/662#issuecomment-1981936303

**Comment by stevieflow** [comment]
@notshi This mockup - I can now see how that is a departure from the way we generate a page such as 

https://d-portal.org/ctrack.html?/participating-org@ref=ET-COA-152#view=main , in line with your comment:

> However, this will be an entirely new section to be added to the site.

If we were to enable such a page, I guess it would be linked from the default view - perhaps similar to your proposal in https://github.com/IATI/D-Portal/issues/661#issuecomment-1981991830 (for example)?

**Comment by notshi** [comment]
> If we were to enable such a page, I guess it would be linked from the default view

Yes, it'll be a new section in the default view somewhere further down the page after Activities ending soon and Ended Activities.

The list can get pretty long ~ XM-DAC-23000 has the most, with 981 narratives!
