### ISSUE TITLE
Call activities activities

### ISSUE THREAD

**Issue by stevieflow** [IATI/D-Portal#664]
When I filter on the homepage I'm helpfully informed that so many *activities* have met my criteria

![Firefox_Screenshot_2024-03-07T11-52-38 900Z](https://github.com/IATI/D-Portal/assets/1209944/1fdd8011-b083-405b-a0cd-ff447d1d2cf0)

This is very useful, especially as d-portal uses IATI data, and the IATI standard has *activities* as it's main unit

However, on accessing that search I get told about *projects*:

![Firefox_Screenshot_2024-03-07T11-54-18 987Z](https://github.com/IATI/D-Portal/assets/1209944/ab1366e9-20b5-461f-9c84-56f662d54580)

Are projects the same as activities?  This confuses me - and I know it confuses others, especially those that have been working hard to publish.... activities!

Therefore - let's not make people think, but call activities activities throughout.  Thanks!

**Comment by notshi** [comment]
Also raised here https://github.com/IATI/D-Portal/issues/645

**Comment by notshi** [comment]
All instances of Projects are now Activities.

If any are missed, do list them here.

**Comment by stevieflow** [comment]
Found one other on the project, sorry - I mean *activity* page:

![Firefox_Screenshot_2024-04-04T07-51-21 233Z](https://github.com/IATI/D-Portal/assets/1209944/528edd68-7236-40e3-86b4-3832c65165ea)

**Comment by notshi** [comment]
Thanks, @stevieflow - that is now fixed.
