### ISSUE TITLE
Update pie charts on main view

### ISSUE THREAD

**Issue by notshi** [IATI/D-Portal#668]
The current pie charts should be updated to look similar to the ones we are using in SAVi (which also used to have pie charts but were replaced when Google phased that out).

We've had this set to go for a while now and thought it a good time to bring up since we're updating things around d-portal. Like the ones in SAVi, this is just using CSS to lay things out so not using any external web components or js.

| Current  | New |
| ------------- | ------------- |
| ![old_graph1](https://github.com/IATI/D-Portal/assets/1515961/8a85e5c4-84f5-4a62-9e2d-2a9652c03ffb) | ![new_graph1](https://github.com/IATI/D-Portal/assets/1515961/0b8feedc-63b0-4d1f-8fbc-5e53ab312f6d) |
| ![old_graph2](https://github.com/IATI/D-Portal/assets/1515961/6e8d4de4-9465-4af1-8279-862831e66dea) | ![new_graph2](https://github.com/IATI/D-Portal/assets/1515961/6cfb9f90-4038-40ab-9aef-bcc97b06f61e) |
| ![old_graph3](https://github.com/IATI/D-Portal/assets/1515961/bc901311-7a4f-4c96-9aaf-5c31491de7c8) | ![new_graph3](https://github.com/IATI/D-Portal/assets/1515961/e7e95fe4-f5dd-48bb-89e2-5106f4502a27) |

**Comment by stevieflow** [comment]
Looks great.  No more pies!

**Comment by stevieflow** [comment]
@notshi could we schedule this to go live on ~17th June?

Thanks

**Comment by notshi** [comment]
Sure - will post here when that happens.

**Comment by notshi** [comment]
This is now live. Do re-open if anything is amiss.
