### ISSUE TITLE
View this Participating Org as a Publisher --> state Reporting Org as well/instead of "Publisher"

### ISSUE THREAD

**Issue by stevieflow** [IATI/D-Portal#669]
Re: new function to see a participating-org as a "publisher":

![Firefox_Screenshot_2024-04-04T16-47-14 159Z](https://github.com/IATI/D-Portal/assets/1209944/a33e3c39-56ee-4df0-ba90-a392850845b5)

So - technically speaking, and in the spirit of d-portal reflecting back the IATI Standard, there's no formal concept (in the standard) of a "publisher".  What we are in fact looking at is the ``reporting-org``

However, also appreciate that publishing IATI data, by publishers (sometimes using _Publisher_!) is a well trodden, and relatable path

Options could be:

- We just say "View this Participating Org as a Reporting Org", or be a bit more helpful with:
-  "View this Participating Org as a Publisher (Reporting Org)"
- and then also on the other button!
-  
@emmajclegg might have an insight too - given the discussion over at https://github.com/younginnovations/iatipublisher/issues/1417#issuecomment-2037667561

Thanks!

**Comment by emmajclegg** [comment]
Do we need to use IATI terms or could we say something plainer like "View data that this organisation has published"

If vetoed, I think "View this Participating Org as a Publisher (Reporting Org)" is the clearer of the two suggestions above. 

The capitilisation of Publisher does risk confusion with the IATI Publisher tool. While working on our IATI Glossary I would like us to be more consistent going forward in the use of publisher vs. [Publisher](https://publisher.iatistandard.org/) !

**Comment by stevieflow** [comment]
Thanks @emmajclegg 

That's a great suggestion.  

Any further thoughts @IsabelBirds ?

**Comment by IsabelBirds** [comment]
And move from "View this Publisher as a Participating Org" to "View this organisation as a Participating Org"?

**Comment by stevieflow** [comment]
Great, thanks @IsabelBirds 

So - @notshi -> please could we:

- when a participating-org/@ref page has a know reporting-org/@ref: "View activities reported by this organisation" 
- when a reporting-org/@ref has records for participating-org/@ref: "View this organisation as a Participating Org"


I'll create a new issue for 

>  "IATI Publishers" to "Reporting organisations"

Thanks @emmajclegg & @IsabelBirds

**Comment by notshi** [comment]
This change is now live - do let me know otherwise.

**Comment by stevieflow** [comment]
@notshi many thanks

I'm not sure the labels are exactly as https://github.com/IATI/D-Portal/issues/669#issuecomment-2039282548

I seem to see:

- View this organisation as a Participating Org 
- View this Participating Org as an organisation 

The second one doesn't make much sense ;)

If these are set by a variable, then maybe change organisation to Reporting Org, so we are fully aligned with the standard?

**Comment by notshi** [comment]
Apologies - missed that entirely for some reason.

> when a participating-org/@ref page has a know reporting-org/@ref: "View activities reported by this organisation"

The label has now been corrected, as above.

**Comment by stevieflow** [comment]
Perfect, thanks @notshi
