### ISSUE TITLE
Add drop down for SDG Goals

### ISSUE THREAD

**Issue by stevieflow** [IATI/D-Portal#680]
To help users discover activities that relate to the SDGs, please include a drop down in the filters that lists the SDG Goals:

https://iatistandard.org/en/iati-standard/203/codelists/unsdg-goals/

In the data itself, there's actually three ways in which an activity can be annotated with an SDG Goal:

- [iati-activities/iati-activity/tag/@code](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/tag/#iati-activities-iati-activity-tag-code) (when ``@vocabulary="2"``)
- [iati-activities/iati-activity/sector/@code](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/sector/#iati-activities-iati-activity-sector-code) (when ``@vocabulary="7"``)
- [iati-activities/iati-activity/transaction/sector/@code](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/transaction/sector/#iati-activities-iati-activity-transaction-sector-code) (when ``@vocabulary="7"``)

@xriss @notshi I think it would be useful to include an activity that meets any of these in the results...

**Comment by stevieflow** [comment]
Update - it would be worth adding an additional dropdown for the SDG Targets: https://codelists.codeforiati.org/UNSDG-Targets/

I don't know if these then would have a "homepage" as per https://github.com/IATI/D-Portal/issues/681 - but it seems the Targets are more, erm, targeted than the Goals, so could give us more specific and relevant data

**Comment by xriss** [comment]
I notice that there is also an SDG Indicators under [sector vocab](https://iatistandard.org/en/iati-standard/203/codelists/sectorvocabulary/).

https://unstats.un.org/sdgs/indicators/indicators-list/

Might as well include this for completion (on the back end) even if you don't want any front end for it.

**Comment by stevieflow** [comment]
Good spot, thanks @xriss

**Comment by notshi** [comment]
SDG Indicator replicated codelist - https://codelists.codeforiati.org/api/json/en/UNSDG-Indicators.json

**Comment by notshi** [comment]
SDG dropdown is now live on the testing site - http://test.d-portal.org/

**Comment by stevieflow** [comment]
Amazing, thanks @notshi 

Can I just double check a logic, please

Here's the results for Goal 1:

![d-portal (9)](https://github.com/user-attachments/assets/3109e0b3-b0d2-492b-8012-a40185aafe8c)

Here's the results for Target 1.1

![d-portal (11)](https://github.com/user-attachments/assets/f9fc6534-608b-4e5b-85e4-98c243f41455)

Am I right in thinking that when I select Goal 1, I am *not* then including any Indicators 1.x ?

Here's the results for Goal 1 *and* Target 1.1 --> which I think means there are no activities that have *both* these values.  Correct?

![d-portal (10)](https://github.com/user-attachments/assets/89002f14-69ce-4864-a849-267cc4653ff5)



Thanks!

**Comment by xriss** [comment]
Slight bug when filtering a goal and a target which should now be fixed. so your last query will be more than 0 activities now. (bit of a query rewrite so if anything else goes strange let me know asap)

But generally yes, I'm not currently auto taging activities with the goal if they only include a target.

**Comment by stevieflow** [comment]
That's great - thanks for the fix @xriss 

My only other feedback is in terms of the labels on the filters - rather than say UNSDG, could we just say SDG (so: "SDG Goals" rather than "UNSDG Goals")?

Thanks

**Comment by notshi** [comment]
Filter labels are now updated.

**Comment by stevieflow** [comment]
Great, thanks - let's make it live!

**Comment by xriss** [comment]
done

**Comment by stevieflow** [comment]
Fantastic, thanks
