### ISSUE TITLE
SDG Goals results page - include the icons?

### ISSUE THREAD

**Issue by stevieflow** [IATI/D-Portal#681]
Related to https://github.com/IATI/D-Portal/issues/680

If / when someone filters for the SDG Goals *and then* goes to the results page --> would / could it be possible that they then access the relevant SDG Goal page on on d-portal, complete with the icons: 

https://www.un.org/sustainabledevelopment/news/communications-material/ ?

I think I see this as an SDG Goal being a "fixed" page, similar to an organisation or country....

Of course, a difficultly would be if someone filters for more than one Goal.  In that case, they would just be at the search results , rather than the specific SDG Goal "homepage"

Hope that is somewhat clear!

**Comment by notshi** [comment]
The SDG filters are now displaying the icons on the results page - does this suffice?

**Comment by stevieflow** [comment]
It's perfect - thanks!
