### ISSUE TITLE
Replace view=donors with view=publishers

### ISSUE THREAD

**Issue by stevieflow** [IATI/D-Portal#684]
I think they may be related to https://github.com/IATI/D-Portal/issues/655

For a page such as https://d-portal.org/ctrack.html?country_code=AO#view=main - this graphic:

![d-portal (20)](https://github.com/user-attachments/assets/8bc8e005-f11a-4bb0-b48d-3cc846abda24)

links to https://d-portal.org/ctrack.html?country_code=AO#view=donors

view=donors is a concept particular to d-portal.  An alternative (and more aligned with IATI data) view does exist:

https://d-portal.org/ctrack.html?country_code=AO#view=publishers

![d-portal (21)](https://github.com/user-attachments/assets/febd34d1-9068-4a56-b6a2-c3bd21b70330)

I suggest replacing the pathways to view=donors with view=publishers

I can imagine this may in turn update the text displayed above the preview graphic (on view=main for example) - but we can take a look in staging at that, and then propose new text (rather than second guess)

And - hopefully this can resolve https://github.com/IATI/D-Portal/issues/655

Thanks

**Comment by stevieflow** [comment]
cc/ @isabelbirds

**Comment by notshi** [comment]
Pathway has been updated and is now live.

CRS is currently hidden for both this and the sector table.

**Comment by stevieflow** [comment]
Thanks @notshi 

Does that mean CRS is now hidden from all views?

**Comment by notshi** [comment]
We've checked and we think so but let us know if we missed anything!

**Comment by stevieflow** [comment]
Thanks
